In [ ]:
import numpy as np ##para poder usar sum, transpose...
import math
        ##Los valores 0 indican que esos huecos están vacíos
sudoku=      [[0,2,4,3],
              [3,0,0,0],
              [2,0,1,4],
              [0,0,0,0]]

##La matriz siempre va a ser de 3x3 (aquí de 2x2 para comprobar, por lo que no hay que comprobar el tamaño del sudoku), así que no hay que comprobar si el número de filas es el mismo que el de columnas, ni si la longitud del sudoku tiene raíz cuadrada entera (4, 9, 16...)
##primero, hay que ver si los datos puestos son correctos (si la matriz es 2 2x2, todos los números deben ser enteros entre 0 y 4)
errorvalor=0
for i in range (0, len(sudoku)):
    for j in range (0, len(sudoku[i])):
        if type(sudoku[i][j])!=int or sudoku[i][j]<0 or sudoku[i][j]>=len(sudoku)+1: ##el valor tiene que ser entero, y estar entre 0 (incluído) y 5 (no incluído)
            #print("ERROR. AL MENOS UN VALOR ES INCORRECTO")
            errorvalor=1
print("¿Todos los valores son correctos? ",errorvalor==0) ##si el valor de errorvalor es 0 (no hay datos incorrectos), podemos continuar

##todos los numeros son del 1 al 4 (el 0 es que no está aún)
if errorvalor!=0:
    print("El sudoku no tiene solución")
else:

    ##ver valores de filas
    filarepetida=0
    for fila in range (0, len(sudoku)): ##debería dar igual si pongo la cantidad de filas o de columnas
        lafila=np.array(sudoku[fila])
        ##valoresfila tendrá la cantidad de veces que aparece cada valor
        valoresfila=np.zeros((len(sudoku)+1), dtype=int)
        for a in range (1, len(valoresfila)):
            valoresfila[a]=(lafila==a).sum()
        for i in range (1, len(valoresfila)):
            if valoresfila[i]>1:
                filarepetida=filarepetida+1
                break
    print("¿Los valores en las filas están sin repetirse (sin contar el 0)?", filarepetida==0) ##Si no hay valores repetidos en ninguna fila (sin contar el 0), podemos continuar

    if filarepetida!=0:
        print("El sudoku no tiene solución")
    else:
    
        ##ver valores de columnas
        matriztraspuesta=np.transpose(sudoku) ##hago la matriz traspuesta para poder acceder directamente a las columnas
        columnarepetida=0
        for columna in range (0, len(matriztraspuesta)):  ##debería dar igual si pongo la cantidad de filas o de columnas, o si pongo el sudoku original o el traspuesto
            lacolumna=np.array(matriztraspuesta[columna])  
            ##valorescolumna tendrá la cantidad de veces que aparece cada valor
            valorescolumna=np.zeros((len(sudoku)+1), dtype=int)
            for a in range (1, len(valorescolumna)):
                valorescolumna[a]=(lacolumna==a).sum()
            for i in range (1, len(valorescolumna)):
                if valorescolumna[i]>1:
                    columnarepetida=columnarepetida+1
                    break
        print("¿Los valores en las columnas están sin repetirse (sin contar el 0)?", columnarepetida==0) ##Si no hay valores repetidos en ninguna columna (sin contar el 0), podemos continuar

        if columnarepetida!=0:
            print("El sudoku no tiene solución")
        else:
            ##ver valores de subceldas (de 2x2 para comprobar. Luego paso a 3x3)
            ##Si el sudoku es de 3x3, hay 9 subceldas. Si el sudoku es de 2x2, hay 4 subceldas (la raíz cuadrada de la longitud del sudoku (9 a 3, 4 a 2))
            sub=int(math.sqrt(len(sudoku)))
            subceldas=[] ##Voy a almacenar en listas la cantidad de cada valor que haya en cada subcelda. Debe haber tantas listas como subceldas
            for i in range (0, sub):
                subceldas.append([]) ##En cada fila, tendremos una lista de listas
                for j in range (0, sub):
                    subceldas[i].append([]) ##En cada columna de cada fila, habrá una lista con la cantidad de cada valor en esa subcelda
                    for k in range (0, len(sudoku)):
                        subceldas[i][j].append(0) ##Cada lista tendrá la misma longitud que posibles valores de una casilla (sin contar el 0)
                        ##Si la matriz fuese de 2x2, tendríamos algo como [[[0, 0, 0, 0], [0, 0, 0, 0]], [[0, 0, 0, 0], [0, 0, 0, 0]]]
                        ##Ahora, vamos a contar las veces que aparece cada valor en cada subcelda (sin contar el 0)
            for i in range (0, len(sudoku)):
                for j in range (0, len(sudoku[i])):
                    if sudoku[i][j]!=0: ##Si el valor de una casilla es 0 (está vacío), no se incrementa ningún contador
                        subceldas[int(i/sub)][int(j/sub)][sudoku[i][j]-1]=subceldas[int(i/sub)][int(j/sub)][sudoku[i][j]-1]+1 
            subceldas=np.array(subceldas)
            subceldarepetida=0
            subceldarepetida=(subceldas>1).sum() ##El contador se incrementará cuando haya algún valor que aparezca más de una vez en una misma subcelda (sin contar el 0)
            print("¿Los valores en las subceldas están sin repetirse (sin contar el 0)?", subceldarepetida==0) ##Si no hay valores repetidos en ninguna subcelda (sin contar el 0), podemos continuar

            if subceldarepetida!=0:
                print("El sudoku no tiene solución")
            else:

                ##Si estamos aquí, es porque la matriz que se nos da tiene todo correcto, por lo que se puede proceder a resolverlo.            
                ##Vamos a hacer una matriz de bool del mismo tamaño del sudoku para incicar qué valores son fijos (vienen ya en la prueba de sudoku dada, y no pueden cambiarse)
                esfijo=np.array(sudoku)
                #esfijo=(esfijo>0) ##Los valores que tengan un valor mayor que 0 están puestos desde el principio, y nunca se deben canbiar
                #print("¿Qué valores son fijos (los que venían ya puestos en el sudoku a resolver)? Están en estas posiciones:")
                print(esfijo) ##Las posiciones cuyo valor sea True son los de los valores fijos (los que venían ya en el enunciado, y nunca se pueden cambiar)

                ultimofila=-1 ##Aquí, voy a quedarme con la última casilla no fija para luego saber cuándo termino
                ultimocolumna=-1
                for m in range (len(sudoku)-1, -1, -1):
                    for n in range (len(sudoku)-1, -1, -1):
                        if sudoku[m][n]==0:
                            ultimofila=m
                            ultimocolumna=n
                            break
                    if ultimofila>=0 and ultimocolumna>=0:
                        break
                if ultimofila<0 or ultimocolumna<0:
                    print("El sudoku ya está completo")
                    print("SOLUCION")
                    print(sudoku)
                else:
                    print("Ultima casilla no fija: [",ultimofila,"][",ultimocolumna,"]")
                        
                    terminado=0
                    ##Aquí, empezamos a resolver el sudoku
                    fil=0
                    while fil<len(sudoku):
                        col=0
                        while col<len(sudoku):
                            if int(esfijo[fil][col])==0: ##Solo hay que trabajar con las posiciones sin valores fijos (tenían un 0 en la prueba se sudoku dada)
                                #sudoku[fil][col]=0 ##¿hará falta esto?
                                while sudoku[fil][col]<len(sudoku)+1: 
                                    sudoku[fil][col]=sudoku[fil][col]+1 ##Le sumamos 1 al valor de esa casilla
                                    print("Probando...")
                                    print(sudoku)
                                    if sudoku[fil][col]>1: ##Del 0 pasa al 1
                                        subceldas[int(fil/sub)][int(col/sub)][sudoku[fil][col]-2]=subceldas[int(fil/sub)][int(col/sub)][sudoku[fil][col]-2]-1 ##Hay una repetición menos del anterior valor en su subcelda
                                    if sudoku[fil][col]==len(sudoku)+1:
                                        break ##Si el valor de una casilla es mayor que el máximo valor posible, es que ningún valor incumple las normas. 
                                    subceldas[int(fil/sub)][int(col/sub)][sudoku[fil][col]-1]=subceldas[int(fil/sub)][int(col/sub)][sudoku[fil][col]-1]+1 ##Hay una repetición más de este valor en su subcelda
                                    if subceldas[int(fil/sub)][int(col/sub)][sudoku[fil][col]-1]>1: ##Comprobamos que su valor no se repite en su subcelda
                                        continue ##Si se repite su valor en su subcelda, directamente pasamos al siguiente valor
                                    lafila=np.array(sudoku[fil]) ##Comprobamos que su valor no se repite en su fila
                                    valorfila=(lafila==sudoku[fil][col]).sum()
                                    if valorfila>1: ##Si se repite su valor en su fila, directamente pasamos al siguiente valor
                                        continue
                                    matriztraspuesta=np.transpose(sudoku) ##Hacemos la matriz traspuesta del sudoku para ir a las columnas
                                    lacolumna=np.array(matriztraspuesta[col])   ##Comprobamos que su valor no se repite en su columna
                                    valorcolumna=(lacolumna==sudoku[fil][col]).sum()
                                    if valorcolumna>1:
                                        continue    ##Si se repite su valor en su columna, directamente pasamos al siguiente valor
                                    ##Si llegamos aquí, el valor es correcto (no incumple ninguna norma)
                                    break ##Esta casilla está bien. Vamos a la siguiente (sales del while de los posibles valores de esa casilla)
                                if sudoku[fil][col]==len(sudoku)+1: #Si esto pasa, hemos probado todos los valores posibles de esa casilla, y todos incumplen alguna norma
                                    sudoku[fil][col]=0  ##Volvemos a poner esa casilla a 0, y volvemos a la anterior casilla que no sea fija para continuar
                                    encontrado=0
                                    while fil>=0:
                                        while col>0:
                                            col=col-1
                                            if int(esfijo[fil][col])==0:
                                                #fil=fil-1
                                                col=col-1 ##Para ajustarlo con la suma que hay al final del while de columnas del programa
                                                encontrado=1
                                                break
                                        if encontrado==1:
                                            break
                                        col=len(sudoku)
                                        fil=fil-1
                                    if fil==-1:
                                        terminado=1 #Variable para indicar que se ha acabado de investigar el sudoku, hubiera o no soluciones
                                        print("No hay más soluciones")
                                        break ##Si llegamos hasta aquí, es que el sudoku no tiene solución
                                else: 
                                    if fil==ultimofila and col==ultimocolumna: ##Aquí, la última casilla no fija ha sido asignada correctamente. Hemos terminado
                                        print("SOLUCION")
                                        print(sudoku)
                                        continue
                                    print("Prometedor")
                            col=col+1
                        if terminado==1:
                            break
                        fil=fil+1


¿Todos los valores son correctos?  True
¿Los valores en las filas están sin repetirse (sin contar el 0)? True
¿Los valores en las columnas están sin repetirse (sin contar el 0)? True
¿Los valores en las subceldas están sin repetirse (sin contar el 0)? True
[[0 2 4 3]
 [3 0 0 0]
 [2 0 1 4]
 [0 0 0 2]]
Ultima casilla no fija: [ 3 ][ 2 ]
Probando...
[[1, 2, 4, 3], [3, 0, 0, 0], [2, 0, 1, 4], [0, 0, 0, 2]]
Prometedor
Probando...
[[1, 2, 4, 3], [3, 1, 0, 0], [2, 0, 1, 4], [0, 0, 0, 2]]
Probando...
[[1, 2, 4, 3], [3, 2, 0, 0], [2, 0, 1, 4], [0, 0, 0, 2]]
Probando...
[[1, 2, 4, 3], [3, 3, 0, 0], [2, 0, 1, 4], [0, 0, 0, 2]]
Probando...
[[1, 2, 4, 3], [3, 4, 0, 0], [2, 0, 1, 4], [0, 0, 0, 2]]
Prometedor
Probando...
[[1, 2, 4, 3], [3, 4, 1, 0], [2, 0, 1, 4], [0, 0, 0, 2]]
Probando...
[[1, 2, 4, 3], [3, 4, 2, 0], [2, 0, 1, 4], [0, 0, 0, 2]]
Prometedor
Probando...
[[1, 2, 4, 3], [3, 4, 2, 1], [2, 0, 1, 4], [0, 0, 0, 2]]
Prometedor
Probando...
[[1, 2, 4, 3], [3, 4, 2, 1], [2, 1, 1, 4], [0, 0, 0, 2]

EXPLICACIÓN SOBRE CÓMO HACEMOS LOS CONTADORES DE LAS SUBCELDAS

Incrementamos 1 al contador del valor que hayamos encontrado en su subcelda

i/sub y j/sub es para poner cada casilla en su subcelda correspondiente. 

Matriz 2x2 Subcelda [0][0]. filas 0-1 y columnas 0-1. Subcelda [0][1]: filas 0-1 y columnas 2-3

Subcelda [1][0]: filas 2-3 y columnas 0-1. Subcelda [1][1]: filas 2-3 y columnas 2-3.  

longitud del sudoku 2x2: raiz(4)=2. 0/2=0, 1/2=0, 2/2=1, 3/2=1

en esfijo[int(i/2)][int(j/2)][elsudoku[i][j]-1], en [elsudoku[i][j]-1], el -1 lo pongo porque en la posición 0 (la primera posición),

cuento las veces que aparece el 1, en la posición 1 (la segunda posición), las veces que aparece 2, ...

In [1]:
import numpy as np
import math
##esta celda la uso para hacer la comprobación de las subceldas
sudoku=      [[0,0,0,0],
              [0,2,0,1],
              [1,4,0,2],
              [2,3,0,0]]
esfijo=np.array(sudoku)
print(esfijo)
ultimofila=-1
ultimocolumna=-1
for m in range (len(sudoku)-1, -1, -1):
    for n in range (len(sudoku)-1, -1, -1):
        if sudoku[m][n]==0:
            ultimofila=m
            ultimocolumna=n
            break
    if ultimofila>0:
        break
if ultimofila>=0 and ultimocolumna>=0:
    print("Ultima casilla no fija: [",m,"][",n,"]")   
else:
    print("El sudoku ya está completo")
    print(sudoku)

[[0 0 0 0]
 [0 2 0 1]
 [1 4 0 2]
 [2 3 0 0]]
Ultima casilla no fija: [ 3 ][ 3 ]
