Práctica 1 **Diseño de Algoritmos**
1. Agustín Prieto
2. Jesús Sanz

In [2]:
from time import time
import random
import statistics
import matplotlib.pyplot
import numpy as np
import pandas as pd

In [3]:
t = time()
1+2
t = time()-t
t

0.0

1. Arrays que estén ordenados
2. Orden inverso
3. Estado aleatorio

Desde 100 elementos hasta 2000 con incremento de 100 en 100. Es decir, un total de 20 mediciones para cada caso.

In [10]:
CONTADOR_PARA_LA_SEMILLA = 0
random.seed(CONTADOR_PARA_LA_SEMILLA)
print(random.randrange(0,5))
CONTADOR_PARA_LA_SEMILLA += 1
random.seed(CONTADOR_PARA_LA_SEMILLA)
print(random.randrange(0,5))

3
1


De esta manera, nuestro código es totalmente reproducible.

Para la media sería interesante lo siguiente

In [11]:
statistics.mean([1,2,3,4,5,6,7,8,9,10])

5.5

Es mejor usar `np.mean`

In [16]:
DATA = np.array([['','Col1','Col2'],
                 ['Row1',1,2],
                 ['Row2',3,4]])
print(pd.DataFrame(data=DATA[1:,1:],
                   index = DATA[1:,0],
                   columns=DATA[0,1:]))

     Col1 Col2
Row1    1    2
Row2    3    4


In [17]:
DATA

array([['', 'Col1', 'Col2'],
       ['Row1', '1', '2'],
       ['Row2', '3', '4']], dtype='<U21')

In [18]:
DATA[0]

array(['', 'Col1', 'Col2'], dtype='<U21')

In [19]:
DATA[0][0]

np.str_('')

Bueno, no nos compliquemos con una BBDD. Hagámoslo lo más sencillo posible y de necesitarla más adelante la volveremos a utilizar. Pero por ahora, simplemente algoritmos.

In [ ]:
def Insercion(a,n):
    for i in range(1,n):
        v=a[i]
        j=i-1
        while j >= 0 and a[j] > v:
            a[j+1] = a[j]
            j=j-1
        a[j+1]=v

In [4]:
mi_lista = np.zeros([10])
#np.append(mi_lista,range(10))
for i in range(10):
    mi_lista[i] = i
mi_lista

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [8]:
mi_lista_invertida = np.zeros([10])
#np.append(mi_lista,range(10))
j = 0
for i in reversed(range(10)):
    mi_lista_invertida[j] = i
    j += 1
mi_lista_invertida

array([9., 8., 7., 6., 5., 4., 3., 2., 1., 0.])

In [44]:
mi_lista_aleatoria = np.zeros([10])
ya_he_puesto_estos = set()
#np.append(mi_lista,range(10))
CONTADOR_PARA_LA_SEMILLA = 0
for i in range(10):
    random.seed(CONTADOR_PARA_LA_SEMILLA)
    CONTADOR_PARA_LA_SEMILLA += 1
    valor_random = random.randrange(0,10)
    while valor_random in ya_he_puesto_estos:
        random.seed(CONTADOR_PARA_LA_SEMILLA)
        CONTADOR_PARA_LA_SEMILLA += 1
        valor_random = random.randrange(0,10)
    mi_lista_aleatoria[valor_random] = i
    ya_he_puesto_estos.add(valor_random)
print(ya_he_puesto_estos)
mi_lista_aleatoria

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}


array([2., 8., 1., 3., 7., 5., 0., 6., 9., 4.])

No sé si admitir números repetidos. Numpy tiene una función que se llama shuffle

Usemos shuffle, no tendremos números repetidos

In [24]:
np.random.shuffle(mi_lista_aleatoria)
mi_lista_aleatoria

array([9., 7., 8., 6., 5., 3., 0., 8., 1., 9.])

Al final lo solucioné de otra forma

# Nuevos horizontes

## ¿Cómo hay que estudiar para trabajar en Google? ¿Y en Facebook?

### Se lo debemos todo al `print('Hello World!')`

#### Farcry 4

😁

In [47]:
for i in range(100,2100,100):
    print(i)

100
200
300
400
500
600
700
800
900
1000
1100
1200
1300
1400
1500
1600
1700
1800
1900
2000


In [56]:
lista = []
print(lista)
lista.append(1)
print(lista)

[]
[1]


In [57]:
tiempos_orden_directo = []
tiempos_orden_inverso = []
tiempos_orden_aleatorio = []

In [ ]:
from time import perf_counter
mi_bbdd = np.array(['','algorithm','time','n_elements'])
for n in range(100,2100,100):
    # ORDEN DIRECTO #
    mi_lista = np.empty([n])
    #np.append(mi_lista,range(10))
    for i in range(n):
        mi_lista[i] = i
    mi_lista
    t = perf_counter()
    Insercion(mi_lista,n)
    t = perf_counter() - t
    


    # ORDEN INVERSO #
    mi_lista_invertida = np.empty([n])
    #np.append(mi_lista,range(10))
    j = 0
    for i in reversed(range(n)):
        mi_lista_invertida[j] = i
        j += 1
    mi_lista_invertida
    # ORDEN ALEATORIO #
    mi_lista_aleatoria = np.empty([n])
    ya_he_puesto_estos = set()
    #np.append(mi_lista,range(10))
    CONTADOR_PARA_LA_SEMILLA = n
    for i in range(n):
        random.seed(CONTADOR_PARA_LA_SEMILLA)
        CONTADOR_PARA_LA_SEMILLA += 1
        valor_random = random.randrange(0,10)
        while valor_random in ya_he_puesto_estos:
            random.seed(CONTADOR_PARA_LA_SEMILLA)
            CONTADOR_PARA_LA_SEMILLA += 1
            valor_random = random.randrange(0,10)
        mi_lista_aleatoria[valor_random] = i
        ya_he_puesto_estos.add(valor_random)
    print(ya_he_puesto_estos)
    mi_lista_aleatoria

In [59]:
np_array = np.array(['','algorithm','time','n_elements'])

In [60]:
df = pd.DataFrame(data=np_array,
                  index = np_array[1:,0],
                  columns=np_array[0,1:])

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [61]:
str(0)

'0'

In [62]:
mi_bb_dd = np.array([1,2])

In [63]:
np.append(mi_bb_dd,[3,4])

array([1, 2, 3, 4])

In [64]:
mi_bb_dd

array([1, 2])

In [65]:
mi_bb_dd.__add__([3,4])

array([4, 6])

In [66]:
np.add(mi_bb_dd,[3,4])

array([4, 6])

In [ ]:
mi_bb_dd.